### ISSUE TITLE
float values are generated with unexpected precision

### ISSUE THREAD

**Issue by nhmtns** [mhaemmerle/excel-to-json#26]
Currently float values in cells are generated with unexpected finer precision. For example, type any float value more than one decimal position (try two or three) and notice values generated in the json file are not exactly the original excel cell values but have much more decimal positions (finer precision). 

I narrowed the issue to this line of code in the "converter.clj" file:

(if-let [result (re-find #"^([-+]?[0-9]+)(\.[0-9]+)?$" value)]
    (if (last result)
      (. Float parseFloat value)
      (. Integer parseInt value))

I hacked above to:
(if-let [result (re-find #"^([-+]?[0-9]+)(\.[0-9]+)?$" value)]
   (if (last result) value value)

and all my float values are now generated correctly as expected.

**Comment by eproxus** [comment]
I'm sorry, but I don't see a difference between the two expressions. Did you pass the wrong line?
